# -*- coding: utf-8 -*-
"""Listas y Diccionarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7JOaMEXRh-PZkUjeIFIaTyA07n95im_

# Listas y Diccionarios - Tipos de Datos Complejos

##Datos Simples
Cadenas-strings
Enteros-int
Decimales-float
Booleano-True o False

##Datos Complejos
Nos permiten almacenar multiples valores a la vez.

Listas-Arrays

Es una coleccion ordenada de elementos, los cuales puede modificar, agregar y eliminar.

Manzanas, Peras, Leche, Carne, Pollo

Diccionarios-Objetos

Es una coleccion de datos desordenada almacenada con clave-valor.

clave   valor
Paula: 3014567898
Pedro: 3105678998
Carlos:3155874569
"""

#Lista

frutas=["Manzana", "Pera", "Naranja"]
print(frutas[1]) #Acceder a un elemento de la lista

frutas[2]="Fresas" #Modificar un elemento de la lista
print(frutas[2])

print(*frutas) #Muestra toda la lista de frutas. * quita los simbolos de la lista

frutas.append("Uva") #append() me permite agregar un elemento a lista, en la ultima posicion
print(*frutas)

frutas.pop(0) #Elimina el ultimo elemento de la lista, o agregando la posicion
print(*frutas)

frutas.remove("Pera") #Elimina un elemento en especifico
print(*frutas)

print(len(frutas)) #Longitud de la lista

#Diccionario

contactos= {
    "Pedro": "310-856-7898",
    "Maria": "315-756-8954",
    "Carlos": "315-523-4574"
}

print("El Contacto de Maria es: ",contactos["Maria"]) #Llamo un elemento por medio de su clave

contactos["Camila"]="310-567-7458" #AGREGANDO UN NUEVO CONTACTO AL DICCIONARIO
print(contactos)

contactos["Maria"]="555-555-5555" #Modificar un elemento

del contactos["Pedro"] #Eliminar un contacto
print(contactos)

"""##Ejercicio 1: Lista de tareas
1. Crea una lista de tareas con al menos 5 elementos.
2. Modifica una de las tareas.
3. Elimina la última tarea de la lista.
4. Agrega una nueva tarea.

##Diccionario de productos
1. Crea un diccionario que almacene nombres de productos y sus precios.
2. Modifica el precio de uno de los productos.
3. Agrega un nuevo producto al diccionario.
4. Elimina un producto del diccionario.


"""

tareas=["Matematicas", "Biologia", "Castellano", "Educacion fisica", "Barrer"]

tareas[2]="Historia"
print(*tareas)

tareas.pop()
print(*tareas)

tareas.append("Trapear")
print(*tareas)

productos={
    "Platano": 1800,
    "Arracacha": 950,
    "Mafafa": 3500
}

productos["Mafafa"]=3000
print(productos)

productos["Lima"]=1500
print(productos)

del productos["Arracacha"]
print(*productos.keys(), *productos.values()) #keys-clave= te muestre todas las claves, values()-muestre solo los valores
print(productos)

contactos={
    "Pedro":{
        "telefono": ["315-456-8925", 3107568974],
        "correo": "pedro@gmail.com",
        "direccion": {
            "Calle": "3A",
            "Barrio": "Principe",
            "Ciudad": "Tuluá"
        }
    },
    "Maria":{
        "telefono": ["315-320-4555"],
        "direccion": {
            "Calle": "32a-15",
            "Barrio":"Siloe",
            "Ciudad": "Cali"
        }
    },
    "Andres":{
        "telefono": ["315-320-4500", "301-456-1234"],
        "correo": ["andres@gmail.com", "andres@pio.edu", "andres@amazon.com"],
        "direccion": {
            "Barrio": "Las vegas",
            "Ciudad": "Yumbo"
        }
    }
}

print(contactos)

contactos["Tatiana"]={ #AGREGAR UN NUEVO CONTACTO
    "telefono": ["315-425-7896", "350-896-1245"],
    "correo": "tatiana@gmail.com"
}

print(*contactos)

print("El telefono de Maria es: ", contactos["Maria"]["telefono"])
print("El segundo telefono de tatiana es: ", contactos["Tatiana"]["telefono"][1])

telefonosTatiana= contactos["Tatiana"]["telefono"]

for telefono in telefonosTatiana:
  print(telefono)

for i, telefono in enumerate(telefonosTatiana, start=1): #Enumerate es una funcion que agrega un
  print(f"Telefono {i}", telefono)                       #contador/indice a cada elemento, start le indicamos desde que
                                                         # numero va a empezar a contar


contactos["Andres"]["Cumpleaños"]="20 de Junio" #agregar una clave o campo nuevo a Andres
print("El cumpleaños de Andres es ",contactos["Andres"]["Cumpleaños"])

contactos["Andres"]["Fecha de nacimiento"]= [20, "Junio", 1995] #Agregar fecha de nacimiento
print("La fecha de nacimiento de Andres es ",*contactos["Andres"]["Fecha de nacimiento"])

yearNacimiento=contactos["Andres"]["Fecha de nacimiento"][2]
print(yearNacimiento)

#Andres es mayor o menor de edad?

del contactos["Pedro"]["telefono"][0] #Eliminar un contacto
print(*contactos["Pedro"]["telefono"])

contactos["Andres"]["correo"].remove("andres@pio.edu")
print(*contactos["Andres"]["correo"])

libros = {
    "Cien Años de Soledad": {
        "autor": "Gabriel García Márquez",
        "año": 1967,
        "género": "Realismo Mágico"
    },
    "Don Quijote de la Mancha": {
        "autor": "Miguel de Cervantes",
        "año": 1605,
        "género": "Novela"
    }
}

inventario = {
    "Manzanas": [100, 150, 200],
    "Naranjas": [50, 80, 120],
    "Peras": [75, 60, 90],
    "Plátanos": [40, 30, 50]
}